/** Describes licensed NPM package */
type Package = {
  /** Package name */
  name: string;
  /** Package url */
  link: string;
  /** Type of license for package */
  licenseType?: string;
  /** Link to custom license for package */
  licenseLink?: string;
};

/** Generated by using `npx license-report` */
export const packages: Package[] = [
  {
    name: 'd3-color',
    link: 'https://github.com/d3/d3-color',
    licenseType: 'ISC',
  },
  {
    name: 'd3-interpolate',
    link: 'https://github.com/d3/d3-interpolate',
    licenseType: 'ISC',
  },
  {
    name: 'textalive-app-api',
    link: 'https://github.com/TextAliveJp/textalive-app-api',
    licenseLink: 'https://github.com/TextAliveJp/textalive-app-api/blob/main/LICENSE.md',
  },
  {
    name: '@sveltejs/vite-plugin-svelte',
    link: 'https://github.com/sveltejs/vite-plugin-svelte',
    licenseType: 'MIT',
  },
  {
    name: '@total-typescript/ts-reset',
    link: 'https://github.com/total-typescript/ts-reset',
    licenseType: 'MIT',
  },
  {
    name: '@tsconfig/svelte',
    link: 'https://github.com/tsconfig/bases',
    licenseType: 'MIT',
  },
  {
    name: '@types/d3-color',
    link: 'https://github.com/DefinitelyTyped/DefinitelyTyped',
    licenseType: 'MIT',
  },
  {
    name: '@types/d3-interpolate',
    link: 'https://github.com/DefinitelyTyped/DefinitelyTyped',
    licenseType: 'MIT',
  },
  {
    name: '@types/node',
    link: 'https://github.com/DefinitelyTyped/DefinitelyTyped',
    licenseType: 'MIT',
  },
  {
    name: '@typescript-eslint/eslint-plugin',
    link: 'https://github.com/typescript-eslint/typescript-eslint',
    licenseType: 'MIT',
  },
  {
    name: '@typescript-eslint/parser',
    link: 'https://github.com/typescript-eslint/typescript-eslint',
    licenseType: 'BSD-2-Clause',
  },
  {
    name: 'autoprefixer',
    link: 'https://github.com/postcss/autoprefixer',
    licenseType: 'MIT',
  },
  {
    name: 'concurrently',
    link: 'https://github.com/open-cli-tools/concurrently',
    licenseType: 'MIT',
  },
  {
    name: 'eslint',
    link: 'https://github.com/eslint/eslint',
    licenseType: 'MIT',
  },
  {
    name: 'eslint-config-prettier',
    link: 'https://github.com/prettier/eslint-config-prettier',
    licenseType: 'MIT',
  },
  {
    name: 'eslint-import-resolver-typescript',
    link: 'https://github.com/import-js/eslint-import-resolver-typescript',
    licenseType: 'ISC',
  },
  {
    name: 'eslint-plugin-import',
    link: 'https://github.com/import-js/eslint-plugin-import',
    licenseType: 'MIT',
  },
  {
    name: 'eslint-plugin-prettier',
    link: 'https://github.com/prettier/eslint-plugin-prettier',
    licenseType: 'MIT',
  },
  {
    name: 'eslint-plugin-svelte',
    link: 'https://github.com/sveltejs/eslint-plugin-svelte',
    licenseType: 'MIT',
  },
  {
    name: 'postcss',
    link: 'https://github.com/postcss/postcss',
    licenseType: 'MIT',
  },
  {
    name: 'postcss-load-config',
    link: 'https://github.com/postcss/postcss-load-config',
    licenseType: 'MIT',
  },
  {
    name: 'prettier',
    link: 'https://github.com/prettier/prettier',
    licenseType: 'MIT',
  },
  {
    name: 'prettier-plugin-svelte',
    link: 'https://github.com/sveltejs/prettier-plugin-svelte',
    licenseType: 'MIT',
  },
  {
    name: 'sass',
    link: 'https://github.com/sass/dart-sass',
    licenseType: 'MIT',
  },
  {
    name: 'stylelint',
    link: 'https://github.com/stylelint/stylelint',
    licenseType: 'MIT',
  },
  {
    name: 'stylelint-config-html',
    link: 'https://github.com/ota-meshi/stylelint-config-html',
    licenseType: 'MIT',
  },
  {
    name: 'stylelint-config-idiomatic-order',
    link: 'https://github.com/ream88/stylelint-config-idiomatic-order',
    licenseType: 'MIT',
  },
  {
    name: 'stylelint-config-prettier-scss',
    link: 'https://github.com/prettier/stylelint-config-prettier-scss',
    licenseType: 'MIT',
  },
  {
    name: 'stylelint-config-standard-scss',
    link: 'https://github.com/stylelint-scss/stylelint-config-standard-scss',
    licenseType: 'MIT',
  },
  {
    name: 'stylelint-order',
    link: 'https://github.com/hudochenkov/stylelint-order',
    licenseType: 'MIT',
  },
  {
    name: 'stylelint-scss',
    link: 'https://github.com/stylelint-scss/stylelint-scss',
    licenseType: 'MIT',
  },
  {
    name: 'svelte',
    link: 'https://github.com/sveltejs/svelte',
    licenseType: 'MIT',
  },
  {
    name: 'svelte-check',
    link: 'https://github.com/sveltejs/language-tools',
    licenseType: 'MIT',
  },
  {
    name: 'svelte-preprocess',
    link: 'https://github.com/sveltejs/svelte-preprocess',
    licenseType: 'MIT',
  },
  {
    name: 'tslib',
    link: 'https://github.com/Microsoft/tslib',
    licenseType: '0BSD',
  },
  {
    name: 'typescript',
    link: 'https://github.com/Microsoft/TypeScript',
    licenseType: 'Apache-2.0',
  },
];
